name: test
on: [push, pull_request]
env:
  CI: true
jobs:
  test:
    name: "Test on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Update
        if: github.ref == 'refs/heads/gh-pages'
        run: |
          git config --global user.name 'azu'
          git config --global user.email 'azuciao@gmail.com'
          ./tools/update-source-data.sh
          ./tools/update-realtime.sh
          ./tools/update-next-draft.sh
          npm run discord
        env:
          GH_TOKEN: ${{ secrets.SHARED_BOT_GITHUB_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
